application: pgur-in
version: 1-0-1
runtime: python27
threadsafe: true
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /favicon\.ico
  static_files: static/images/logo.ico
  upload: static/images/logo\.ico
  expiration: "365d"

- url: /scripts/(.+)\.js
  static_files: static/scripts/\1.js
  upload: static/scripts/(.*\.(js))

- url: /styles/(.+)\.css
  static_files: static/stylesheets/\1.css
  upload: static/stylesheets/(.*\.(css))

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "365d"

- url: /images
  static_dir: static/images
  expiration: "365d"

- url: /fonts
  static_dir: static/fonts
  expiration: "365d"

- url: /cron/.*
  script: route.APPLICATION
  login: admin
  secure: always

# Endpoints handler
- url: /_ah/spi/.*
  script: route.API

- url: /.*
  script: route.APPLICATION

inbound_services:
- warmup

libraries:
- name: webapp2
  version: latest
- name: endpoints
  version: latest

error_handlers:
  - file: templates/default_error.html

  - error_code: over_quota
    file: templates/over_quota.html

builtins:
- deferred: on
- remote_api: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(node_modules/.*)
- ^(package.json)
- ^(Gruntfile.js)
- ^(.*/)?.*\.md$
- ^(.*/)?COPYING$
- ^(.*/)?LICENSE$
- ^(.*/)?Makefile$
- ^(.*/)?README$
- ^(.*/)?AUTHORS$
- ^(.*/)?PATENTS$
- ^(.*/)?marked.*$
